---
title: 'project '
author: Nouran
date: '2021-07-24'
slug: project
categories:
  - Basics
  - caret
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-07-24T19:12:40-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
```{r,warning=FALSE , message=FALSE,echo=FALSE,results=FALSE}
library("DataExplorer")
library("janitor")
library("tidyr")
library("tidyverse")
library("dplyr")
library("yardstick")
library("ggplot2")
library("tidymodels")
library("Information")
library("Scorecard")

```

```{r}

credit_bureau_data<-read_csv("Credit_Bureau.csv")%>%
# Cleaning the names of the columns
clean_names() %>%
# removing the rows where the values of performance_tag are  Nas
drop_na(performance_tag)

# converting the independent categorical variables to be stored as factors based on Listendata.com
credit_bureau_data$ presence_of_open_home_loan <- factor(credit_bureau_data$ presence_of_open_home_loan)
credit_bureau_data$ presence_of_open_auto_loan <- factor(credit_bureau_data$ presence_of_open_auto_loan)

# Converting the application ID variable to character
credit_bureau_data$ application_id <- as.character(credit_bureau_data$ application_id)


glimpse(credit_bureau_data)
str(credit_bureau_data)
summary(credit_bureau_data)


```


```{r}
## Data Exploration 
#create_report(credit_bureau_data)
```

```{r}

## splitting the data for training and testing
set.seed(130)


data_split <- initial_split(credit_bureau_data,prop = 0.75,strata = performance_tag)

training_data<- data_split%>%
  training()

testing_data <- data_split%>%
  testing()


```


```{r}
IV <- create_infotables(data=training_data, y="performance_tag", bins=20, parallel=FALSE)

IV_Value = data.frame(IV$Summary)

#print(IV$Tables$avgas_cc_utilization_in_last_12_months, row.names=FALSE)
avgas_cc_utilization_in_last_12_months = data.frame(IV$Tables$avgas_cc_utilization_in_last_12_months)


#Removing the variables with Information value less than 0.02 that is presence_of_open_auto_loan from the training and testing sets
reduced_training_data<- training_data%>% 
  select(-presence_of_open_auto_loan,-presence_of_open_home_loan,-application_id)
reduced_testing_data<- testing_data%>% 
  select(-presence_of_open_auto_loan,-presence_of_open_home_loan,-application_id)
```

```{r}
plot_infotables(IV, "avgas_cc_utilization_in_last_12_months")

plot_infotables(IV, IV$Summary$Variable[1:16], same_scale=FALSE,show_values = TRUE)




```



```{r}

# Bin all variables of the data frame (apart from the target variable)
# with default parameter settings
binning <- woe.binning(training_data, 'performance_tag', training_data)
# Plot the binned variables
woe.binning.plot(binning)
# Tabulate the binned variables
tabulate.binning <- woe.binning.table(binning)
tabulate.binning
# Deploy the binning solution to the data frame
# (i.e. add binned variables and corresponding WOE variables)
# df.with.binned.vars.added <- woe.binning.deploy(df, binning,
# add.woe.or.dum.var='woe')
```


```{r}
library("scorecard")
bins <- woebin(dt = training_data,y = "performance_tag")
```




```{r}
woebin_plot(bins$avgas_cc_utilization_in_last_12_months)

```
```{r}
WOE_temp <- woebin_ply(training_data,bins)

View(WOE_temp)

View(training_data[is.na(training_data$No.of.dependents),])

IV_values <- iv(dt = training_data,y = "performance_tag")
(IV_values)
```

