<!DOCTYPE html><html lang="en-us" >

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  
  
    <meta name="generator" content="Wowchemy 5.2.0 for Hugo" />
  

  

  
  
  
  
  
    
    
    
  
  

  <meta name="author" content="Nouran Mostafa" />

  
  
  
    
  
  <meta name="description" content="Part 1 Cross- Validation for Logistic and linear Regression model:The GoalThe goal behind this study is to use the cross-validation resampling method to evaluate the performance of our logistic and linear regression models." />

  
  <link rel="alternate" hreflang="en-us" href="/post/a03-resampling-methods/" />

  







  




  
  
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  

  
  
  
    <meta name="theme-color" content="#1565c0" />
  

  
  

  
  
  
  
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha256-FMvZuGapsJLjouA6k7Eo2lusoAX9i0ShlWFG6qt7SLc=" crossorigin="anonymous">

    
    
    
    
      
      
    
    
    

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/github.min.css" crossorigin="anonymous" title="hl-light" media="print" onload="this.media='all'">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/styles/dracula.min.css" crossorigin="anonymous" title="hl-dark" media="print" onload="this.media='all'" disabled>
        
      
    

    
    
    
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.css" integrity="sha512-1xoFisiGdy9nvho8EgXuXvnpR5GAMSjFwp40gSRE3NwdUdIMIKuPa7bqoUhLD0O/5tPNhteAsE5XyyMi5reQVA==" crossorigin="anonymous" media="print" onload="this.media='all'">
    

    

    
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
      
      

      
      
        
      

      
    
      
      

      
      

      
    
      
      

      
      

      
    
  

  
  
  
    
      
      <link rel="preload" as="style" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&family=Roboto+Mono&family=Roboto:wght@400;700&display=swap" media="print" onload="this.media='all'">
    
  

  
  
  
  
  
  <link rel="stylesheet" href="/css/wowchemy.7145a9a307b7b6e0cf40149bdecd66b5.css" />

  



  

  

  




  
  
  

  

  
    <link rel="manifest" href="/index.webmanifest" />
  

  <link rel="icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_32x32_fill_lanczos_center_2.png" />
  <link rel="apple-touch-icon" type="image/png" href="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_180x180_fill_lanczos_center_2.png" />

  <link rel="canonical" href="/post/a03-resampling-methods/" />

  
  
  
  
  
  
  
  
    
    
  
  
  <meta property="twitter:card" content="summary" />
  
  <meta property="og:site_name" content="HOME" />
  <meta property="og:url" content="/post/a03-resampling-methods/" />
  <meta property="og:title" content="A03 Resampling Methods | HOME" />
  <meta property="og:description" content="Part 1 Cross- Validation for Logistic and linear Regression model:The GoalThe goal behind this study is to use the cross-validation resampling method to evaluate the performance of our logistic and linear regression models." /><meta property="og:image" content="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_512x512_fill_lanczos_center_2.png" />
    <meta property="twitter:image" content="/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_512x512_fill_lanczos_center_2.png" /><meta property="og:locale" content="en-us" />
  
    
      <meta
        property="article:published_time"
        content="2021-07-22T00:00:00&#43;00:00"
      />
    
    <meta property="article:modified_time" content="2021-07-22T09:31:53-03:00">
  

  


    






  




<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "/post/a03-resampling-methods/"
  },
  "headline": "A03 Resampling Methods",
  
  "datePublished": "2021-07-22T00:00:00Z",
  "dateModified": "2021-07-22T09:31:53-03:00",
  
  "author": {
    "@type": "Person",
    "name": "Nouran Mostafa"
  },
  
  "publisher": {
    "@type": "Organization",
    "name": "HOME",
    "logo": {
      "@type": "ImageObject",
      "url": "/media/icon_hua2ec155b4296a9c9791d015323e16eb5_11927_192x192_fill_lanczos_center_2.png"
    }
  },
  "description": "Part 1 Cross- Validation for Logistic and linear Regression model:\rThe Goal\rThe goal behind this study is to use the cross-validation resampling method to evaluate the performance of our logistic and linear regression models."
}
</script>

  

  

  

  





  <title>A03 Resampling Methods | HOME</title>
</head>


<body id="top" data-spy="scroll" data-offset="70" data-target="#TableOfContents" class="page-wrapper   " data-wc-page-id="9f0cc6489905ed71be1e3a1268234ba3" >

  
  
  
  
  
  
  
  
  
  <script src="/js/wowchemy-init.min.b8153d4570dcbb34350a2a846dba8c03.js"></script>

  


<aside class="search-modal" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#" aria-label="Close"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" spellcheck="false" type="search" class="form-control"
        aria-label="Search...">
        
      </div>

      
      

      

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>



  <div class="page-header">
    












<nav class="navbar navbar-expand-lg navbar-light compensate-for-scrollbar" id="navbar-main">
  <div class="container-xl">

    
    <div class="d-none d-lg-inline-flex">
      <a class="navbar-brand" href="/">HOME</a>
    </div>
    

    

    
    <div class="navbar-brand-mobile-wrapper d-inline-flex d-lg-none">
      <a class="navbar-brand" href="/">HOME</a>
    </div>
    

    
    
    <div class="navbar-collapse main-menu-item collapse justify-content-start" id="navbar-content">

      
      <ul class="navbar-nav d-md-inline-flex">
        

      

        
      </ul>
    </div>

    <ul class="nav-icons navbar-nav flex-row ml-auto d-flex pl-md-2">

      
      
        
          
          <li class="nav-item d-none d-lg-inline-flex">
            <a class="nav-link" href="https://twitter.com/NouranM85487915" data-toggle="tooltip" data-placement="bottom" title="Follow me on Twitter" target="_blank" rel="noopener" aria-label="Follow me on Twitter">
              <i class="fab fa-twitter" aria-hidden="true"></i>
            </a>
          </li>
        
      

      
      

      
      
      <li class="nav-item dropdown theme-dropdown">
        <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-label="Display preferences">
          <i class="fas fa-moon" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu">
          <a href="#" class="dropdown-item js-set-theme-light">
            <span>Light</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-dark">
            <span>Dark</span>
          </a>
          <a href="#" class="dropdown-item js-set-theme-auto">
            <span>Automatic</span>
          </a>
        </div>
      </li>
      

      
      

    </ul>

  </div>
</nav>


  </div>

  <div class="page-body">
    <article class="article">

  












  

  
  
  
<div class="article-container pt-3">
  <h1>A03 Resampling Methods</h1>

  

  
    


<div class="article-metadata">

  
  

  
  <span class="article-date">
    
    
      
          Last updated on
      
    
    Jul 22, 2021
  </span>
  

  

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    9 min read
  </span>
  

  
  
  
  
  
  

  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder mr-1"></i><a href="/category/ggplot2/">ggplot2</a>, <a href="/category/tidymodels/">tidymodels</a>, <a href="/category/tideverse/">Tideverse</a>, <a href="/category/caret/">caret</a>, <a href="/category/yardstick/">yardstick</a>, <a href="/category/dplyr/">dplyr</a></span>
  

</div>

    





  
</div>



  <div class="article-container">

    <div class="article-style">
      
<script src="/post/a03-resampling-methods/index_files/header-attrs/header-attrs.js"></script>


<div id="part-1-cross--validation-for-logistic-and-linear-regression-model" class="section level2">
<h2>Part 1 Cross- Validation for Logistic and linear Regression model:</h2>
<div id="the-goal" class="section level3">
<h3>The Goal</h3>
<p>The goal behind this study is to use the cross-validation resampling method to evaluate the performance of our logistic and linear regression models.</p>
</div>
</div>
<div id="first-for-logistic-regression-model" class="section level2">
<h2>First For Logistic Regression Model:</h2>
<div id="the-data" class="section level3">
<h3>The data</h3>
<p>The data used in this study was obtained from UCI website and we specifically used the Bank-full.csv dataset.</p>
</div>
<div id="splitting-the-data-to-training-and-testing-splits" class="section level3">
<h3>splitting the data to training and testing splits</h3>
<p>In this step we are going to split the data on hands so that 3/4 of the data would be assigned for training and 1/4 of the data would be assigned for testing.</p>
</div>
<div id="create-the-logistic-regression-model" class="section level3">
<h3>create the logistic regression model</h3>
<p>Creating the logistic regression model that will be used to identify whether a customer will subscribe to a term deposit or not.</p>
</div>
<div id="creating-the-recipe" class="section level3">
<h3>creating the recipe</h3>
<p>creating the suitable recipe to apply feature engineering to our data</p>
</div>
<div id="create-workflow" class="section level3">
<h3>Create workflow</h3>
<p>Create a workflow that combine the model and the recipe.</p>
</div>
<div id="fit-the-model" class="section level3">
<h3>Fit the model</h3>
<p>Train and fitting the model using the training split of the data.</p>
<pre><code>## # A tibble: 35 x 5
##    term              estimate std.error statistic  p.value
##    &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
##  1 (Intercept)         -1.65     0.126     -13.1  3.88e-39
##  2 duration             1.06     0.0189     56.3  0       
##  3 campaign            -0.272    0.0358     -7.60 2.94e-14
##  4 job_blue.collar     -0.368    0.0833     -4.41 1.01e- 5
##  5 job_entrepreneur    -0.367    0.143      -2.57 1.01e- 2
##  6 job_housemaid       -0.441    0.150      -2.95 3.20e- 3
##  7 job_management      -0.243    0.0838     -2.90 3.72e- 3
##  8 job_retired          0.166    0.0997      1.67 9.57e- 2
##  9 job_self.employed   -0.330    0.128      -2.57 1.03e- 2
## 10 job_services        -0.242    0.0971     -2.49 1.27e- 2
## 11 job_student          0.521    0.119       4.37 1.23e- 5
## 12 job_technician      -0.183    0.0794     -2.31 2.11e- 2
## # ... with 23 more rows</code></pre>
</div>
<div id="make-predictions-for-training-data" class="section level3">
<h3>Make predictions for training data</h3>
<p>Using the trained model for prediction where the training data is used.</p>
<pre><code>## # A tibble: 33,907 x 11
##    .pred_class y     job          education housing loan  contact month duration
##    &lt;fct&gt;       &lt;fct&gt; &lt;fct&gt;        &lt;fct&gt;     &lt;fct&gt;   &lt;fct&gt; &lt;fct&gt;   &lt;fct&gt;    &lt;int&gt;
##  1 no          no    management   tertiary  yes     no    unknown may        261
##  2 no          no    entrepreneur secondary yes     yes   unknown may         76
##  3 no          no    blue-collar  unknown   yes     no    unknown may         92
##  4 no          no    unknown      unknown   no      no    unknown may        198
##  5 no          no    management   tertiary  yes     no    unknown may        139
##  6 no          no    technician   secondary yes     no    unknown may         55
##  7 no          no    admin.       secondary yes     no    unknown may        137
##  8 no          no    technician   secondary yes     no    unknown may        517
##  9 no          no    technician   unknown   yes     no    unknown may         71
## 10 no          no    services     secondary yes     no    unknown may        174
## # ... with 33,897 more rows, and 2 more variables: campaign &lt;int&gt;,
## #   poutcome &lt;fct&gt;</code></pre>
</div>
<div id="evaluate-performance-on-tarining-data" class="section level3">
<h3>Evaluate performance on tarining data</h3>
<p>Evaluate the performance of the model on the training data.</p>
<pre><code>##           Truth
## Prediction    no   yes
##        no  29193  2595
##        yes   748  1371</code></pre>
<pre><code>## # A tibble: 3 x 3
##   .metric  .estimator .estimate
##   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
## 1 accuracy binary         0.901
## 2 sens     binary         0.975
## 3 spec     binary         0.346</code></pre>
</div>
<div id="make-predictions-for-testing-data" class="section level3">
<h3>Make predictions for testing data</h3>
<p>Using the trained model for prediction where the testing data is used.</p>
<pre><code>## # A tibble: 11,304 x 11
##    .pred_class y     job          education housing loan  contact month duration
##    &lt;fct&gt;       &lt;fct&gt; &lt;fct&gt;        &lt;fct&gt;     &lt;fct&gt;   &lt;fct&gt; &lt;fct&gt;   &lt;fct&gt;    &lt;int&gt;
##  1 no          no    technician   secondary yes     no    unknown may        151
##  2 no          no    management   tertiary  yes     yes   unknown may        217
##  3 no          no    entrepreneur tertiary  yes     no    unknown may        380
##  4 no          no    retired      primary   yes     no    unknown may         50
##  5 no          no    admin.       secondary yes     no    unknown may        222
##  6 no          no    retired      primary   yes     no    unknown may        353
##  7 no          no    admin.       unknown   yes     no    unknown may         98
##  8 no          no    blue-collar  primary   yes     no    unknown may         38
##  9 no          no    retired      primary   yes     no    unknown may        219
## 10 no          no    technician   secondary yes     yes   unknown may        348
## # ... with 11,294 more rows, and 2 more variables: campaign &lt;int&gt;,
## #   poutcome &lt;fct&gt;</code></pre>
</div>
<div id="evaluate-performance-on-testing-data" class="section level3">
<h3>Evaluate performance on testing data</h3>
<p>Evaluate the performance of the model on the testing data.</p>
<pre><code>##           Truth
## Prediction   no  yes
##        no  9754  875
##        yes  227  448</code></pre>
<pre><code>## # A tibble: 3 x 3
##   .metric  .estimator .estimate
##   &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
## 1 accuracy binary         0.903
## 2 sens     binary         0.977
## 3 spec     binary         0.339</code></pre>
</div>
</div>
<div id="apply-cross-validation-method-for-model-evaluation" class="section level2">
<h2>Apply Cross Validation method for model evaluation</h2>
<div id="split-data-into-folds" class="section level3">
<h3>Split data into folds</h3>
<p>The train data is split-ted into 5 folds</p>
</div>
<div id="fit-resamples" class="section level3">
<h3>Fit resamples</h3>
<p>Fit the folds into the workflow.</p>
</div>
<div id="collect-cv-metrics" class="section level3">
<h3>Collect CV metrics</h3>
<p>Show the metrics resulted from Cross-Validation process</p>
<pre><code>## # A tibble: 2 x 6
##   .metric  .estimator  mean     n std_err .config             
##   &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1 accuracy binary     0.902     5 0.00165 Preprocessor1_Model1
## 2 roc_auc  binary     0.904     5 0.00174 Preprocessor1_Model1</code></pre>
</div>
<div id="conclusion" class="section level3">
<h3>Conclusion</h3>
<p>The accuracy associated with the model using the training data is 90.1%, that associated with the model using the testing data is 90.3% and that associated with the model using cross validation resampling method is 90.1%. The accuracy in the testing data is quite good and it is slightly better than the accuracy in the training data which indicates that our model is not exposed to overfitting on the training data, also the accuracy resulted from the testing data is comparable with the accuracy we got from cross-validation resampling method that indicates that our model is working properly.</p>
</div>
</div>
<div id="second-for-linear-regression-model" class="section level2">
<h2>Second For Linear Regression Model:</h2>
<div id="the-diamond-ring-data" class="section level3">
<h3>The diamond ring data</h3>
<p>In this part we used the diamond ring data.</p>
<pre><code>## Rows: 440
## Columns: 9
## $ price         &lt;dbl&gt; 3000, 3000, 3004, 3004, 3006, 3007, 3008, 3010, 3012, 30~
## $ carat         &lt;dbl&gt; 0.92, 0.92, 0.82, 0.81, 0.90, 0.87, 0.80, 0.84, 0.80, 0.~
## $ colour        &lt;chr&gt; &quot;I&quot;, &quot;I&quot;, &quot;F&quot;, &quot;G&quot;, &quot;J&quot;, &quot;F&quot;, &quot;D&quot;, &quot;F&quot;, &quot;D&quot;, &quot;D&quot;, &quot;G&quot;, &quot;~
## $ clarity       &lt;chr&gt; &quot;SI2&quot;, &quot;SI2&quot;, &quot;SI2&quot;, &quot;SI1&quot;, &quot;VS2&quot;, &quot;SI2&quot;, &quot;SI2&quot;, &quot;SI1&quot;, ~
## $ cut           &lt;chr&gt; &quot;G&quot;, &quot;V&quot;, &quot;I&quot;, &quot;I&quot;, &quot;V&quot;, &quot;I&quot;, &quot;I&quot;, &quot;G&quot;, &quot;V&quot;, &quot;V&quot;, &quot;I&quot;, &quot;~
## $ certification &lt;chr&gt; &quot;AGS&quot;, &quot;AGS&quot;, &quot;GIA&quot;, &quot;GIA&quot;, &quot;GIA&quot;, &quot;AGS&quot;, &quot;GIA&quot;, &quot;GIA&quot;, ~
## $ polish        &lt;chr&gt; &quot;V&quot;, &quot;G&quot;, &quot;X&quot;, &quot;X&quot;, &quot;V&quot;, &quot;G&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;~
## $ symmetry      &lt;chr&gt; &quot;V&quot;, &quot;G&quot;, &quot;X&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;V&quot;, &quot;X&quot;, &quot;V&quot;, &quot;~
## $ wholesaler    &lt;chr&gt; &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;1&quot;, &quot;~</code></pre>
</div>
<div id="splitting-the-data-to-training-and-testing-splits-1" class="section level3">
<h3>splitting the data to training and testing splits</h3>
<p>In this step we are going to split the data on hands so that 3/4 of the data would be assigned for training and 1/4 of the data would be assigned for testing.</p>
</div>
<div id="create-the-linear-regression-model" class="section level3">
<h3>create the linear regression model</h3>
<p>Creating the linear regression model that will be used to predict the price of the diamond ring of interest.</p>
</div>
<div id="creating-the-recipe-1" class="section level3">
<h3>creating the recipe</h3>
<p>creating the suitable recipe to apply feature engineering to our data</p>
</div>
<div id="create-workflow-1" class="section level3">
<h3>Create workflow</h3>
<p>Create a workflow that combine the model and the recipe.</p>
</div>
<div id="fit-the-model-1" class="section level3">
<h3>Fit the model</h3>
<p>Train and fitting the model using the training split of the data.</p>
</div>
<div id="make-predictions-for-training-data-1" class="section level3">
<h3>Make predictions for training data</h3>
<p>Using the trained model for prediction where the training data is used.</p>
<pre><code>## # A tibble: 328 x 10
##    .pred price carat colour clarity cut   certification polish symmetry
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;   
##  1 350.    190  0.09 D      SI1     X     IGI           G      G       
##  2 134.    160  0.09 E      SI1     I     IGI           G      G       
##  3  85.6   160  0.09 F      SI1     I     IGI           V      G       
##  4 134.    180  0.09 E      SI1     I     IGI           G      G       
##  5 227.    190  0.09 E      VS1     I     IGI           V      G       
##  6 196.    330  0.1  E      VS2     V     IGI           V      G       
##  7 192.    180  0.1  E      VS2     X     IGI           G      G       
##  8  88.9   160  0.1  F      SI1     X     IGI           G      G       
##  9 142.    160  0.1  E      SI1     V     IGI           G      G       
## 10  60.7   190  0.1  E      SI2     G     IGI           V      G       
## # ... with 318 more rows, and 1 more variable: wholesaler &lt;chr&gt;</code></pre>
</div>
<div id="evaluate-performance-on-tarining-data-1" class="section level3">
<h3>Evaluate performance on tarining data</h3>
<p>Evaluate the performance of the model on the training data.</p>
<p><em>R-squared</em></p>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rsq     standard       0.986</code></pre>
<p><img src="/post/a03-resampling-methods/index_files/figure-html/unnamed-chunk-22-1.png" width="672" />
<em>RMSE</em></p>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard        136.</code></pre>
</div>
<div id="make-predictions-for-testing-data-1" class="section level3">
<h3>Make predictions for testing data</h3>
<p>Using the trained model for prediction where the testing data is used.</p>
<pre><code>## # A tibble: 112 x 10
##    .pred price carat colour clarity cut   certification polish symmetry
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;   
##  1 3035.  3000  0.92 I      SI2     G     AGS           V      V       
##  2 3028.  3000  0.92 I      SI2     V     AGS           G      G       
##  3 3088.  3006  0.9  J      VS2     V     GIA           V      V       
##  4 3027.  3027  0.81 F      SI1     V     AGS           V      V       
##  5 2957.  3036  0.81 H      SI1     V     GIA           G      V       
##  6 3235.  3041  0.83 D      SI2     G     GIA           G      G       
##  7 3052.  3044  0.91 I      SI2     I     GIA           V      V       
##  8 3000.  3062  0.8  E      SI2     V     GIA           V      V       
##  9   NA   3081  0.9  F      SI2     F     GIA           v      G       
## 10 2956.  3089  0.91 H      SI2     F     GIA           V      V       
## # ... with 102 more rows, and 1 more variable: wholesaler &lt;chr&gt;</code></pre>
</div>
<div id="evaluate-performance-on-testing-data-1" class="section level3">
<h3>Evaluate performance on testing data</h3>
<p>Evaluate the performance of the model on the testing data.</p>
<p><em>R-squared</em></p>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rsq     standard       0.983</code></pre>
<p><img src="/post/a03-resampling-methods/index_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p><em>RMSE</em></p>
<pre><code>## # A tibble: 1 x 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard        157.</code></pre>
</div>
</div>
<div id="apply-cross-validation-method-for-model-evaluation-1" class="section level2">
<h2>Apply Cross Validation method for model evaluation</h2>
<div id="split-data-into-folds-1" class="section level3">
<h3>Split data into folds</h3>
<p>The train data is split-ted into 5 folds</p>
</div>
<div id="fit-resamples-1" class="section level3">
<h3>Fit resamples</h3>
<p>Fit the folds into the workflow.</p>
</div>
<div id="collect-cv-metrics-1" class="section level3">
<h3>Collect CV metrics</h3>
<p>Show the metrics resulted from Cross-Validation process</p>
<pre><code>## # A tibble: 2 x 6
##   .metric .estimator    mean     n std_err .config             
##   &lt;chr&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard   153.        5 5.07    Preprocessor1_Model1
## 2 rsq     standard     0.983     5 0.00123 Preprocessor1_Model1</code></pre>
</div>
<div id="conclusion-1" class="section level3">
<h3>Conclusion</h3>
<p>The rsq associated with the model on the training data is 0.99, that associated with the model in the testing data is 0.98 and that associated with the model using cross validation is 0.98. From that we can see that our model is performing good.</p>
</div>
</div>

    </div>

    








<div class="share-box" aria-hidden="true">
  <ul class="share">
    
      
      
      
        
      
      
      
      <li>
        <a href="https://twitter.com/intent/tweet?url=/post/a03-resampling-methods/&amp;text=A03%20Resampling%20Methods" target="_blank" rel="noopener" class="share-btn-twitter">
          <i class="fab fa-twitter"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.facebook.com/sharer.php?u=/post/a03-resampling-methods/&amp;t=A03%20Resampling%20Methods" target="_blank" rel="noopener" class="share-btn-facebook">
          <i class="fab fa-facebook"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="mailto:?subject=A03%20Resampling%20Methods&amp;body=/post/a03-resampling-methods/" target="_blank" rel="noopener" class="share-btn-email">
          <i class="fas fa-envelope"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://www.linkedin.com/shareArticle?url=/post/a03-resampling-methods/&amp;title=A03%20Resampling%20Methods" target="_blank" rel="noopener" class="share-btn-linkedin">
          <i class="fab fa-linkedin-in"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="whatsapp://send?text=A03%20Resampling%20Methods%20/post/a03-resampling-methods/" target="_blank" rel="noopener" class="share-btn-whatsapp">
          <i class="fab fa-whatsapp"></i>
        </a>
      </li>
    
      
      
      
        
      
      
      
      <li>
        <a href="https://service.weibo.com/share/share.php?url=/post/a03-resampling-methods/&amp;title=A03%20Resampling%20Methods" target="_blank" rel="noopener" class="share-btn-weibo">
          <i class="fab fa-weibo"></i>
        </a>
      </li>
    
  </ul>
</div>











  
  



  
  
  
    
  
  
  
  <div class="media author-card content-widget-hr">
    
      
      <img class="avatar mr-3 avatar-circle" src="/author/nouran-mostafa/avatar_hu87b681ad54a12849109b4b507d9003fa_46844_270x270_fill_q75_lanczos_center.jpg" alt="Nouran Mostafa">
    

    <div class="media-body">
      <h5 class="card-title">Nouran Mostafa</h5>
      
      
      <ul class="network-icon" aria-hidden="true">
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://twitter.com/NouranM85487915" target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://github.com/N0o0UR" target="_blank" rel="noopener">
        <i class="fab fa-github"></i>
      </a>
    </li>
  
    
    
    
      
    
    
    
    
    
      
    
    <li>
      <a href="https://www.linkedin.com/in/nouran-mostafa/" target="_blank" rel="noopener">
        <i class="fab fa-linkedin"></i>
      </a>
    </li>
  
</ul>

    </div>
  </div>
















  
  
  <div class="article-widget content-widget-hr">
    <h3>Related</h3>
    <ul>
      
      <li><a href="/post/the-project/">Project </a></li>
      
      <li><a href="/post/a05-exploratory-data-analysis/">A05  Exploratory Data Analysis</a></li>
      
    </ul>
  </div>
  





  </div>
</article>
  </div>

  <div class="page-footer">
    
    
    <div class="container">
      <footer class="site-footer">

  

  

  

  
  






  <p class="powered-by">
    
    
    
      
      
      
      
      
      
      Published with <a href="https://wowchemy.com/?utm_campaign=poweredby" target="_blank" rel="noopener">Wowchemy</a> — the free, <a href="https://github.com/wowchemy/wowchemy-hugo-modules" target="_blank" rel="noopener">open source</a> website builder that empowers creators.
    
  </p>
</footer>

    </div>
    
  </div>

  
<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

      

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/instant.page/5.1.0/instantpage.min.js" integrity="sha512-1+qUtKoh9XZW7j+6LhRMAyOrgSQKenQ4mluTR+cvxXjP1Z54RxZuzstR/H9kgPXQsVB8IW7DMDFUJpzLjvhGSQ==" crossorigin="anonymous"></script>

      
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.4/imagesloaded.pkgd.min.js" integrity="sha256-lqvxZrPLtfffUl2G/e7szqSvPBILGbwmsGE1MKlOi0Q=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js" integrity="sha256-CBrpuqrMhXwcLLUd5tvQ4euBHCdh7wGlDfNz8vbu/iI=" crossorigin="anonymous"></script>
      

      
      

      

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/highlight.min.js" integrity="sha512-TDKKr+IvoqZnPzc3l35hdjpHD0m+b2EC2SrLEgKDRWpxf2rFCxemkgvJ5kfU48ip+Y+m2XVKyOCD85ybtlZDmw==" crossorigin="anonymous"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/r.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/python.min.js"></script>
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.2.0/languages/latex.min.js"></script>
        
      

    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.7.1/leaflet.min.js" integrity="sha512-SeiQaaDh73yrb56sTW/RgVdi/mMqNeM2oBwubFHagc5BkixSpP1fvqF47mKzPGWYSSy4RwbBunrJBQ4Co8fRWA==" crossorigin="anonymous"></script>
    

    
    

    
    
    
      
      <script id="search-hit-fuse-template" type="text/x-template">
        <div class="search-hit" id="summary-{{key}}">
          <div class="search-hit-content">
            <div class="search-hit-name">
              <a href="{{relpermalink}}">{{title}}</a>
              <div class="article-metadata search-hit-type">{{type}}</div>
              <p class="search-hit-description">{{snippet}}</p>
            </div>
          </div>
        </div>
      </script>
      
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
      
    

    
    

    
    
    
    

    
    <script src="/js/bootstrap.bundle.min.6aed84840afc03ab4d5750157f69c120.js"></script>

    
    
      
      
      
      
      
      
      
    

    
    
    
    
    
    
    
    
      
      
    
    
    <script src="/en/js/wowchemy.min.4bba0826db6409c865d2e7b99039d6d0.js"></script>

    
  <script async defer src="https://buttons.github.io/buttons.js"></script>




</body>
</html>
